### ISSUE TITLE
WBI: muanal notification when irrigation starts automatically

### ISSUE THREAD

**Issue by sverleysen** [hhaim/hass#12]
When the irrigation is triggered automatically, I receive the corrent notification, but I also get the manual start notification.

Example of the logs:
2020-04-05 07:00:00.208066 INFO wb_irrigation:  irrigation event for p1
2020-04-05 07:00:01.170713 INFO wb_irrigation: 07:00:01 irrigation time tap p1 timer 15 min
2020-04-05 07:00:02.629552 INFO wb_irrigation: turn on by user p1 30 min 
2020-04-05 07:00:02.776351 INFO wb_irrigation: 07:00:02 irrigation time tap p1 manual 30 min
2020-04-05 07:15:58.068002 INFO wb_irrigation:  irrigation stop for p1 on

**Comment by hhaim** [comment]
@sverleysen I will try to fix this

**Comment by Arquiteto** [comment]
I encountered the same problem. To troubleshoot I added lines that returns current tap["handle"] state to log. It seems like the handle is not passed to the do_button_change function.

> 2020-04-15 15:02:00.041464 INFO wb_irrigation:  irrigation event for r2
> 2020-04-15 15:02:00.607240 INFO wb_irrigation: 15:02:00 irrigation time tap r2 timer 13 min
> 2020-04-15 15:02:04.547680 INFO wb_irrigation:  Irrigation handle in start_tap fnc 473c08b8b70941cdad4567b0324e3f89
> 2020-04-15 15:02:04.630963 INFO wb_irrigation:  Irrigation handle in start_tap after turn_on fnc 473c08b8b70941cdad4567b0324e3f89
> 2020-04-15 15:02:04.670903 INFO wb_irrigation:  Irrigation handle in do_button change fnc None
> 2020-04-15 15:02:04.678366 INFO wb_irrigation: turn on by user r2 25 min 
> 2020-04-15 15:02:04.737613 INFO wb_irrigation: 15:02:04 irrigation time tap r2 manual 25 min

**Comment by hhaim** [comment]
@Arquiteto 
Something is **wrong** with AppDaemon. 

In case manual trigger, tap[“handle”] is None. In case of auto it is set to the handle of run_in (not none). In your case it is None and it can’t be.

I would add a log. I’m using 3.0.5 AppDaemon version maybe the API was changed ??


== add log here
tap["handle"] = self.run_in(self.time_cb_event_stop, 
                        duration_sec, 
                        tap=tap,clear_queue=clear_queue)

**Comment by hhaim** [comment]
@Arquiteto i just saw the logs. What is your AppDaemon version?

**Comment by hhaim** [comment]
I would try to limit the AppDaemon number of threads to 1.
“threads: 1“

**Comment by sverleysen** [comment]
> @Arquiteto i just saw the logs. What is your AppDaemon version?

I'm using AppDeamon 4.

**Comment by Arquiteto** [comment]
> @Arquiteto i just saw the logs. What is your AppDaemon version?
AppDaemon 4, I'll try with ver 3

I added some lines to log what's happening in start_tap function
```
        self.log(" Log no 1 in start_tap before writing handle {}".format(tap["handle"]))
        tap["handle"] = self.run_in(self.time_cb_event_stop,
                        duration_sec,
                        tap=tap,clear_queue=clear_queue)
        self.log(" Log no 2 in start_tap after writing handle {}".format(tap["handle"]))  # Debug
        tap["start"] = self.read_water_sensor ()
        self.turn_on(tap["switch"])
        self.log(" Log no 3 in start_tap after turning on {}".format(tap["handle"]))  # Debug
```

And in do_button_change function
```
    tap = kwargs['tap']
        self.log(" Log no 4 in do_button change {}".format(tap["handle"])) #Debug
        if tap["handle"] is None:
           # manual start
            if new == "on":
```

This is the result

> 2020-04-16 09:19:00.060596 INFO wb_irrigation:  irrigation event for r1
> 2020-04-16 09:19:00.193427 INFO wb_irrigation: 09:19:00 irrigation time tap r1 timer 9 min
> 2020-04-16 09:19:01.202169 INFO wb_irrigation:  Log no 1 in start_tap before writing handle None
> 2020-04-16 09:19:01.212563 INFO wb_irrigation:  Log no 2 in start_tap after writing handle f64284b0d3b54567befcf912148f71a6
> 2020-04-16 09:19:01.296693 INFO wb_irrigation:  Log no 3 in start_tap after turning on f64284b0d3b54567befcf912148f71a6
> 2020-04-16 09:19:01.325292 INFO wb_irrigation:  Log no 4 in do_button change None
> 2020-04-16 09:19:01.331655 INFO wb_irrigation: turn on by user r1 15 min 
> 2020-04-16 09:19:01.390961 INFO wb_irrigation: 09:19:01 irrigation time tap r1 manual 15 min
> 2020-04-16 09:19:02.169487 INFO wb_irrigation:  Log no 1 in start_tap before writing handle None
> 2020-04-16 09:19:02.179627 INFO wb_irrigation:  Log no 2 in start_tap after writing handle 46aae443038046738a6af383fefab482
> 2020-04-16 09:19:02.218669 INFO wb_irrigation:  Log no 3 in start_tap after turning on 46aae443038046738a6af383fefab482

**Comment by Arquiteto** [comment]
> I would try to limit the AppDaemon number of threads to 1.
> “threads: 1“

Seems like that might be the problem. This appears in log while starting AppDaemon v4
> 2020-04-16 09:27:23.222863 WARNING AppDaemon: Threads directive is deprecated apps - will be pinned. Use total_threads if you want to unpin your apps

**Comment by hhaim** [comment]
@sverleysen thanks for reporting. 
Could you check this fix? I need to find time to upgrade to v4.0 
https://github.com/hhaim/hass/commit/57b1e70811a1ba38aab165bd6a29f6e0565a5356
I didn't have time to verify it, but I can think of a reason why the code didn't work for you

**Comment by hhaim** [comment]
> > I would try to limit the AppDaemon number of threads to 1.
> > “threads: 1“
> 
> Seems like that might be the problem. This appears in log while starting AppDaemon v4
> 
> > 2020-04-16 09:27:23.222863 WARNING AppDaemon: Threads directive is deprecated apps - will be pinned. Use total_threads if you want to unpin your apps

Actually, this might **not** be the problem. This was my suggestion to the maintainer of AppDaemon and it seems he agreed to move to pinned mode which has much less issues. 
The issue relates to some other design issues, please try my fix

**Comment by Arquiteto** [comment]
Yeah, I just tried the fix. It seems it works. Thank you very much.

**Comment by hhaim** [comment]
@Arquiteto thanks for testing. I will integrate it to master

**Comment by hhaim** [comment]
rebased.
