### ISSUE TITLE
FAO56 sensor value not updating?

### ISSUE THREAD

**Issue by jeroenterheerdt** [hhaim/hass#16]
The fao56 sensor's value is 0 all the time, but the same sensor as a 'fao56' attribute and that is updated regularly. Is this expected behavior or should the sensor not be 0?
![image](https://user-images.githubusercontent.com/8188990/81020865-a95f9c80-8e1e-11ea-9df3-82309182b53f.png)

**Comment by hhaim** [comment]
@jeroenterheerdt fao56 is a key sensor. You have an issue in reading it from weather station
change  ```debug: true ``` in the component from verifying the values/errors 

Because it is a very slow update (every hour) I would change the timer to see the effect 

(you should reload HASS)

```
wb_irrigation:
  api_key: !secret openweathermap_key
  rain_factor: 90
  max_ev: 3000
  min_ev: -1500.0
  name: "wb_irrigation"
  debug: false
  longitude: !secret accurate_longitude
  latitude: !secret accurate_latitude
  elevation: !secret accurate_elevation
  taps:
    - name: p1
    - name: p2

```

**Comment by jeroenterheerdt** [comment]
Thanks @hhaim. After the night, the irrigation_fao56 sensor got a value, so it seems something is working. irrigation_tap1 is now also set. What is the expected behavior? What do these values mean and when are they reset? How can I debug if everything is working correctly? I do not see anything related to fao in the data from the weather station.
Also, it looks like I am missing the ev_day sensor?

This is my config:
```
api_key: !secret openweathermap_key
rain_factor: 90
max_ev: 3000
min_ev: -1500.0
name: "Irrigation"
debug: true
longitude: XXX
latitude: XXX
elevation: XXX
taps:
 - name: tap1
```

and this is what is shown in the interface:

![image](https://user-images.githubusercontent.com/8188990/81116071-9b228680-8ed9-11ea-9395-f5eddc65eaf5.png)

![image](https://user-images.githubusercontent.com/8188990/81116030-8a721080-8ed9-11ea-9fba-15a0a2fc76a1.png)

**Comment by jeroenterheerdt** [comment]
Status as of now: ![image](https://user-images.githubusercontent.com/8188990/81089621-6e5a7900-8eb1-11ea-8927-68b9ec2b7521.png)
![image](https://user-images.githubusercontent.com/8188990/81089652-76b2b400-8eb1-11ea-8285-17762c405a72.png)

**Comment by hhaim** [comment]
@jeroenterheerdt it works. The sensor value is being updated   only at midnight. however you can see a **field** called **fao56** which is being updated every hour (in the picture you sent it is 29.9)

See how to tune it in this wiki:
https://github.com/hhaim/hass/wiki/Weather-based-irrigation

**Comment by jeroenterheerdt** [comment]
thanks for explaining. I am curious to understand how your solution works without knowledge of the sprinkler system. Its great that we know how much moisture is lost and what we need to add, but without knowledge of how much we add per hour/minute how can the system ever know how long it needs to run? Other systems need that input. I read your wiki, etc, but still am curious about this.

**Comment by hhaim** [comment]
@jeroenterheerdt good question. First this system works for my garden without intervention. The idea behind it that you already know/tuned your garden for the hottest days. This WBI is just a mechanism tune watering **down** due to rain or low Ev.
It maybe not accurate as other system but much better than manual tunning

**Comment by jeroenterheerdt** [comment]
thanks @hhaim! I appreciate your response and your hard work. I will take this forward and see if I can come up with something that does what I need :)

**Comment by jeroenterheerdt** [comment]
hi @hhaim - I noticed you normalized the ev value to a scale of 100 - 400 a day. It looks like this function does that:
`# multiply it by 2 to norm it to 300ev a day 
           fao56 =  2 * estimate_fao56(day_of_year,
                                   t,
                                   self._elevation,
                                   self._lat,
                                   rh,
                                   ws,
                                   atmos_pres);`

so... if I wanted to denormalize it, can I just divide this value by 300? I am trying to compare the value to what is reported here: http://www.rainmaster.com/historicET.aspx (for example using zipcode 98019):
![image](https://user-images.githubusercontent.com/8188990/81440235-8be34900-9124-11ea-888b-a1d87be6103c.png)
also, what does your EV value report? inch per day? cm per day? mm per day?

My plan is to basically make this calculation in HA: https://www.rainbird.com/professionals/irrigation-scheduling-use-et-save-water, which seems to me like what I am looking for using the input from your work to get the actual daily EV/ET value and then figuring out how long the irrigation should run to counter this.

many thanks for helping!

**Comment by hhaim** [comment]
@jeroenterheerdt fao56 is not between 100-400 it could be 500 in hot day or even more see the documentation.  There is a factor to convert mm/day to total ev. It is just a empirical factor you need to add.

**Comment by jeroenterheerdt** [comment]
@hhaim I think I get it - fao56 is mm/day, so what's the factor to convert that to ev? Is it in your code somewhere? And again, why did you multiple the fao56 by two? I do not seem to understand the reasoning behind it.

**Comment by hhaim** [comment]
@jeroenterheerdt My fao56 is a bit of optimization of the documentation. In the original calculation it is done once a day and I could do it every hour. So I remove the time factor and just aggregate each hour the fao56 value. I multiply it by 2 to get to my old simple ev formula range (200ev instead of 100ev). The absolute value is **important** to be aligned with hottest ev value days value you provide for normalization.

**Comment by jeroenterheerdt** [comment]
@hhaim thanks - I understand the part that you calculate fao56 every hour and just sum it to get a daily value. What I am not getting is how to compare this value to other EV values. I mean, if you look at the graphic a couple of posts up in this thread which is for my zipcode, the reference _daily EV_ value is 0.16, but the FAO56 from your calculation easily reaches 1.6 _an hour_. Hence my confusion - what do you actually calculate here? I mean, if you look at example 19 in [chapter 4 of the original paper](http://www.fao.org/3/X0490E/x0490e08.htm#chapter%204%20%20%20determination%20of%20eto) in a much hotter climate the hourly FAO is 0.63, nowhere near the 1.6 I am getting for my mountain climate. It kind of looks like the calculations you did do not transfer over to my situation.

**Comment by hhaim** [comment]
@jeroenterheerdt my calculation every hour is the daily ETo so it is in range of 8 for hot day. Multiply it by 12 is ~100 ev. Then I just multiply it by x2 (~200 in hot day)

The reason I multiply it by factor 2 is to be in the same range of Blaney-Criddle simplest model (~200 for hot day) - this is the model I’ve started with and it didn’t work but I still ask the user to put the ev of hottest day by this model.

Now that you pointed this out, I might be accumulating twice the Fao56 sensor but somehow it just works ..

What is your daily value right now?

**Comment by jeroenterheerdt** [comment]
daily fao56  value is 114.7 on a sunny day. That is nowhere near comparable to reference ETo values. My approach is the following: I want to use the reference ETo and calculations to create a water budget that will allow me to very precisely (and applicable to all situations) control the irrigation by knowing how many liters per minute it uses. That part is all done. What I don't seem to get to work is getting the FAO values from your code to be in the same order of magnitude. I mean, rainfall is in mm / hour or per day, so ideally I am looking to get FAO values in mm / hour or per day. your code just seems to return very high FAO values.

**Comment by hhaim** [comment]
@jeroenterheerdt  to convert Rain  mm/day to ev I use a factor (you can provide it in the yaml) of 90. Meaning 2mm/day would be converted to 200ev which is like skipping one day of irrigation. Give it a try a tune it

**Comment by jeroenterheerdt** [comment]
thanks - also, I think I spotted a bug in your code: you set t to temperature in kelvin where it expects a temperature in Celcius. `t=pyeto.convert.celsius2kelvin(temp_c),`.

Many thanks for being so responsive while I work through this.

**Comment by hhaim** [comment]
t should be in Kelvin and i don’t see the issue

**Comment by jeroenterheerdt** [comment]
you're right, [the documentation](https://pyeto.readthedocs.io/en/latest/api.html) says it needs to be in kelvin, the source says it needs to be in celsius. confusing ;)
