### ISSUE TITLE
Question and some spelling mistakes

### ISSUE THREAD

**Issue by Phibins** [hhaim/hass#18]
First off, this is really cool! Thanks for taking the time to share your code and write a very clear wiki!

**Question**:
I see you used the 

> Sonoff 4 ch pro to switch on/off the taps

But how does a relay turn the taps on/off... Im a bit new, but i understand the relays are just the on/off switch. They must be attached to some device that turns the tap on/off. If so, what is the device you use to turn the water on and off?

I know you linked to the [Orbit Sprinkler](https://www.amazon.com/Orbit-Sprinkler-System-1-Inch-57467/dp/B0013I62XC/ref=sr_1_15?keywords=Sprinkler+Valve&qid=1558094079&s=gateway&sr=8-15) but this doesnt seem like something electronic that can be controlled by a relay.

Unless i misunderstood?

**A couple spelling mistakes**:

several instances of typo: "liter=litter"  (i [edited ](https://github.com/hhaim/hass/compare/master...Phibins:patch-2?expand=1)the page)

[typo: "use-case"="usec-case" ](https://github.com/hhaim/hass/wiki/Weather-based-irrigation#tasmota-configuration) (im new to github - i couldn't, or dont know how, to edit the wiki page)

Also i rotated the image for you (although it could be more clear) for [item #3](https://github.com/hhaim/hass/wiki/Weather-based-irrigation#sonoff-4-ch). https://i.imgur.com/1XJbmQa.png

Toda Raba!

P.S. 

I know you must be busy, but pictures of your devices for out door irrigation would be a reallly cool addition to this page :)... you can just throw them in anywhere

**Comment by hhaim** [comment]
@Phibins I had a working system that wasn't smart (it was programmed with specific duration and specific schedule) I have something similar to Orbit Sprinkler. I just replaced the computer with a Sonoff 4ch. 
It works like that, If there is **no** power to the sprinkler it will be closed. If you put **24vAC** it will open the sprinkler. 


So I took the old power and connected it throw the Sonoff "cold" switch. HA control the on/off and Tasmota make sure it will be closed after timeout (loss of network)


[I have this sprinkler](https://www.hagarin.co.il/%D7%9E%D7%95%D7%A6%D7%A8-1998-%D7%91%D7%A8%D7%96-%D7%97%D7%A9%D7%9E%D7%9C%D7%99-3-4-%D7%A4%D7%9C%D7%A1%D7%98%D7%99%D7%A7.aspx)


![image](https://user-images.githubusercontent.com/13034429/82909443-f93f0880-9f71-11ea-96e7-bb71b5b2fb9d.png)


Thanks for the spelling correction

**Comment by Phibins** [comment]
I want ot use your brilliant code for the watering shedule, but need to get it working with my garden hose unfortunatly.

So if I buy something like [this ](https://www.amazon.ca/dp/B07BKZ3YZY) will I be able to hack it together with your smart schedule?

How do you know the flow rate coming out of the tap when its on? _Is that a constant I would need to add to the program?_

I am planning to have a garden hose lead to 4-5 flower-beds with a small (low-flow) sprinkler spout like this 
![image](https://user-images.githubusercontent.com/37847843/82911034-64201d80-9f39-11ea-890b-0f1bccaed9da.png)

So i imagine a lot less water comes out compared toyour system, can i adjust for this?

**Comment by hhaim** [comment]
@Phibins my solution just automatically tune the duration of the irrigation, it does not change the scheduling. I came from a point that I had a manual irrigation system that worked and could be tuned for **specific** weather point. The problem was that I needed to tune it for specific hot days or specific times that it was raining, this is not needed anymore.
You should consult with a gardener for the design, then you need to connect the sprinklers on/off switch to HA for automatic tunning.

On my garden it works like a charm for a year now, I don’t remember when I manually touched it

**Comment by hhaim** [comment]
This is the irrigation computer that was replaced https://galconc.com/product/8000/
With a simple sonoff + HA
