### ISSUE TITLE
Water_monitor integration not working

### ISSUE THREAD

**Issue by SeByDocKy** [hhaim/hass#4]
During my config checking got

Configuration invalid
Integration not found: water_monitor

here is my setup I used

in configuration.yaml
''
variable: !include variable.yaml

water_monitor:
  module: heat_app
  class: CWaterMonitor
  sensor_water_total: sensor.water_total
  sensor_water_leak_detector: variable.water_leak_detector
  #sensor_water_bursts: variable.water_bursts
  sensor_water_bursts: variable.water_usage_bursts
  watchdog_duration_min: 50
  watchdog_leakage_ticks: 3
  max_day: 2000
  max_burst_l0: 400
  max_burst_l1: 600
  taps_switchs: [ switch.wbi_p1] # when one of them is enabled move to burstl1  ''

in sensor.yaml

``- platform: tasmota
  name: "water_total"
  stopic: ECS
  id: 1
  max_valid_diff: 2000
 # unit_of_measurement: 'l'
  icon: mdi:water
  expire_after: 300
  value_template: "{{ ((0 + (value))|int) }}"

- platform: tasmota
  name: "water_total_norm"
  stopic: ECS
  id: 1
  unit_of_measurement: 'l'
  icon: mdi:water
  expire_after: 300
  value_template: "{{ ((0 + (value/400.0))|float)| round(2) }}"

in variable.yaml
''
water_leak_detector:
  value: 0
  restore: true
  attributes:
    friendly_name: 'water leaks detector'
    unit_of_measurement: "l"

water_bursts:
  value: 0
  restore: true
  attributes:
    friendly_name: 'water usage bursts'
    unit_of_measurement: "l"
''

**Comment by hhaim** [comment]
You should install AppDaemon and its parts  see [here](https://github.com/hhaim/hass/wiki/How-to-Install-this-project-AppDaemon-apps)

**Comment by SeByDocKy** [comment]
> You should install AppDaemon and its parts see [here](https://github.com/hhaim/hass/wiki/How-to-Install-this-project-AppDaemon-apps)

What is this particular API key  ?

**Comment by hhaim** [comment]
I've updated the wiki 
https://github.com/hhaim/hass/wiki/How-to-Install-this-project-AppDaemon-apps

**Comment by SeByDocKy** [comment]
Ok now I can see the new variables in grafana but no data (yet) collectect with....
