### ISSUE TITLE
Basic setup with smart switch

### ISSUE THREAD

**Issue by sverleysen** [hhaim/hass#6]
Is it possible to use this Weather based irrigation solution to toggle an smart switch? I have a very basic setup for my sprinklers, just a smart switch that will turn on/off my water pump. I was looking for something like this and it’s all I want, but I need to be able to set an other action.

Can you give me some directions to get started? I installed the component, I see all the sensors, but I can't find a way to include my smart switch.
So I want/need to be able to start the water pump (smart switch) when the ev_day (or fao56?) reaches a certain value at a certain time. Turn off the switch after x minutes. I guess another value must be updated with the amount of water that is used to update the ev_day (or fao56?)?

Also a small suggestion, maybe rename some off the sensors. If you are new into this, ev_day, fao56, p1, wp1,... doesn't say much. If you give this a more user friendly name, people will understand it more easily.

Thanks in advance!

**Comment by hhaim** [comment]
Hi @sverleysen 
It does exactly what you described and yes, it modular enough for any smart switch . I think you are missing the AppDaemon part.
Have you looked into the wiki? There is a detailed explanation there.

**Comment by sverleysen** [comment]
Hi, 
Thanks! I missed that part. I though it was linked with the Tasmota.
I got it all setup now.  But I have some questions:
![wbi](https://user-images.githubusercontent.com/6018080/61443750-67767000-a94a-11e9-9139-48246d4aee30.JPG)
I don't understand some values/sensors. Can you please explain a bit? 
I guess the value of Pipe1 is used to trigger the irrigation, but whats the difference with wb_irrigation_fao56? 
The Rain sensor (the 3th in the picture is the rain from the last day? Last few days, ...? And whats the difference with the Rain today sensor?
P1_hours is just to know when the sprinkers have been used and for how long?
P1_l is how much liters is used? I what timespan? And how can I set this?

After the sprinklers have been turned back off, I guess the system must know how much water has been used to update the EV value? How can I set that?

Btw, the switch linked to the system is just a dummy switch. Its not linked to the water pump yet. I want to test it out first and see how it works. :) 

Thanks!

**Comment by hhaim** [comment]
Fao56 - is the day evaporations in ev units (0-500) 500 is very hot
Px - is the per pipe queue level in ev units, rain will increase. Once it is negative there would be an irrigation 
rain- there are two sensors. Accumulated per day mm and per hour.
P_hours/litter is accumulated(it is going always up). This is how grafana like it.

For the litter to work you should have a sensor to measure it (see other wiki)

The dummy switch is a good idea.

One suggestion, before you enable it with a real sensor make sure there is a mechanism to shut it in case of any failure (network/power)

**Comment by sverleysen** [comment]
Thanks for the info. I think I start to understand everything. 
I don't have the option to monitor my waterflow, but I know how much water is used by my water pump, x l/h. Is there a way I can use this data? x l/h, I use the sprinkers for example 10min, so do a calculation around that?
Also isn't there a need to know how much water is used for the dimensions of the grass? 20l for 1m² is a big difference with 20l for 100m².

**Comment by hhaim** [comment]
You can do it using grafana. I didn’t publish the query on water irrigation but you can learn the idea from the water monitor wiki

**Comment by hhaim** [comment]
![7709137D-4D50-453E-AF6E-8FEB615A604E](https://user-images.githubusercontent.com/13034429/61522157-76c4ee80-aa1a-11e9-8579-2d4b6f309318.jpeg)

This is an example how it should look like with two taps.

**Comment by sverleysen** [comment]
It looks like I got it all setup now. Thanks!
