### ISSUE TITLE
wb_irrigation_rain sensor isn't correct

### ISSUE THREAD

**Issue by sverleysen** [hhaim/hass#8]
Hi,

My sensor wb_irrigation_rain has a value of 5mm while there was no rain today. 
![image](https://user-images.githubusercontent.com/6018080/62197796-ca232f00-b380-11e9-8887-dbd43dce2cd0.png)

The sensor.owm_rain also show no rain for the last 24 hours.
![image](https://user-images.githubusercontent.com/6018080/62197764-be376d00-b380-11e9-8099-60e535775983.png)

Kind regards,
Sen

**Comment by hhaim** [comment]
The rain indication is based on the response from OWP.
The fact that your sensor does not show it, means that in **one** response there was a rain indication and in another there was not !
 
If you want to help just enable ```debug:true``` and send the logs from OWM. (it will be sent as an error)

    if self._debug and self._type == TYPE_RAIN:
            _LOGGER.error(" wbi_raw_data {} ".format(d))

```
wb_irrigation:
  api_key: !secret openweathermap_key
  rain_factor: 90
  max_ev: 3000 
  min_ev: -1500.0
  name: "wb_irrigation"
  debug: false                          <<<<<<<<< move this to true
  longitude: !secret accurate_longitude
  latitude: !secret accurate_latitude
  elevation: !secret accurate_elevation
```

**Comment by sverleysen** [comment]
I understand that the calculation is done based on the response from OWM. I just noticed it isn't always accurate and that's why I'm letting you know. So maybe we can find a better way together. Because yesterday 'your' sensor said it rained 6mm (based on OWM prediction data) but there wasn't any rain, so my queue value went up a lot (because of the rain), and no irrigation was done. But the queue was low enough to have started the irrigation when there was no rain.

OWM prediction said it was going to rain at 3:00 PM, and so the WB_irrigation_rain sensor value just went up at 3:00. But the owm_rain sensor is again not reporting any rain (what is correct).

The output from the OWM logs at 3:00 PM:
 wbi_raw_data {'coord': {'lon': 4.33, 'lat': 51.36}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'base': 'stations', 'main': {'temp': 21.48, 'pressure': 1016, 'humidity': 64, 'temp_min': 19.44, 'temp_max': 23.89}, 'visibility': 10000, 'wind': {'speed': 6.2, 'deg': 270}, 'clouds': {'all': 75}, 'dt': 1564664400, 'sys': {'type': 1, 'id': 1560, 'message': 0.0107, 'country': 'BE', 'sunrise': 1564632379, 'sunset': 1564687896}, 'timezone': 7200, 'id': 2802243, 'name': 'Berendrecht', 'cod': 200}

**Comment by hhaim** [comment]
def rain_desc_to_mm (self,code):
        CONVERT= {500:1.0,
                  501:2.0,
                  502:5.0,
                  503:20.0,
                  504:60.0,
                  511:5.0,
                  520:5.0,
                  521:5.0,
                  522:20.0,
                  531:50.0}

You change code 500/501 to be zero

**Comment by hhaim** [comment]
@sverleysen did it help?

**Comment by sverleysen** [comment]
@hhaim, yeah it's a bit more accurate. But still a lot of false positives. 
I was now testing an other sensor for measuring the amount of rain in the last hour/24 hours. Is there a way I can use this sensors if they are more accurate?

**Comment by hhaim** [comment]
With a small change it would be possible. 
Can you elaborate on the "more accurate" with numbers?
I think it still have a value with a few false positive as it is much better than manual method.

**Comment by sverleysen** [comment]
This are values from today:
Your sensors:
![image](https://user-images.githubusercontent.com/6018080/62945509-22c1e580-bddf-11e9-933f-d776975ef17f.png)

The new sensors I'm testing (buienradar, something local for Belgium and the Netherlands):
![image](https://user-images.githubusercontent.com/6018080/62945532-34a38880-bddf-11e9-88be-60155fe88e72.png)

I completely agree that your way is better than a manual method, thats why I started using it. But i'm just trying to make it as good as possible. 

I had a few days that wasn't a drop off rain, but the sensor was at +80mm off rain on that day. So my queue when back to the max value, instead of turning on the sprinklers that night.

**Comment by hhaim** [comment]
Understood. In my case it is very accurate (the rain). I think it's related to your location. 
In my case there is a station nearby. The +80mm error could make it not usable. It is very big error

**Comment by sverleysen** [comment]
Is there any plan on updating the code so another sensor can be used?

**Comment by hhaim** [comment]
I could add this support, it should be easy.
just make sure you have a sensor that accumulate  the total mm or rain and it is always **going up**

**Comment by hhaim** [comment]
```
wb_irrigation:
  api_key: !secret openweathermap_key
  rain_factor: 90
  max_ev: 3000 
  min_ev: -1500.0
  name: "wb_irrigation"
  external_rain_sensor: sensor.my_sensor  <<<<<<<<<< your sensor 
  longitude: !secret accurate_longitude
  latitude: !secret accurate_latitude
  elevation: !secret accurate_elevation
  taps: 
    - name: p1
    - name: p2
```

**Comment by sverleysen** [comment]
So the accumulate sensor never resets? It always keeps going up, over multiple days/weeks/months...?
I will make the sensor and test it.
Thanks!

**Comment by hhaim** [comment]
@sverleysen 
Correct, the sensor required by wb_irrigation should never reset. 
You can always add another sensor that reset

**Comment by hhaim** [comment]
Could you share a comparison between your sensor to  OWM ?

**Comment by sverleysen** [comment]
I'm trying to create a sensor to accumulate the values. If you know a way, it would be nice :)
When I have it up and running, I will provide the comparison. Does wb_irrigation exposes a sensor with the accumated value? Or do I have to make 1?

**Comment by hhaim** [comment]
@sverleysen  What your sensor does right now?

**Comment by sverleysen** [comment]
I have 2 sensors from the new waether sensor (buienradar). 1 for the amount of rain in the last hour and 1 for the last 24 hours.
![image](https://user-images.githubusercontent.com/6018080/64115120-19e58380-cd8f-11e9-9001-4898e96dec83.png)
![image](https://user-images.githubusercontent.com/6018080/64115153-28339f80-cd8f-11e9-9289-36ecc7b8e5f1.png)

As you can see, the values doesn't reset after the period, it slowly goes back down.
Now I need to find a way to create a new sensor that keeps adding the amount of rain (and handles the value difference if it goes down) and never resets.

I was looking into history stats, but that required a states property, which I can't use. Because the state of the sensor is the value.

**Comment by hhaim** [comment]
@sverleysen this could work too with a minimum error (might miss a few mm per day in the transitions)

**Comment by sverleysen** [comment]
Do you know how I can accumate the values?

**Comment by hhaim** [comment]
You need to write a script that trigger when there is a change in the value and add the def if it is positive to a new sensor. I'm usually writing code in hass or appDaemon. Never have written a script

**Comment by hhaim** [comment]
@sverleysen I think last hour will be fine

1. Apply this patch  
https://github.com/hhaim/hass/commit/330410da6d7265b65f74d1809323914687d40a1c

2.  

Add your last hour rain sensor to wb_irrigation 
like this:
```
external_rain_1h: sensor.br_rain_last_hour
```

full example like this
```
wb_irrigation:
  api_key: !secret openweathermap_key
  rain_factor: 90
  max_ev: 3000 
  min_ev: -1500.0
  name: "wb_irrigation"
  external_rain_1h: sensor.br_rain_last_hour
  longitude: !secret accurate_longitude
  latitude: !secret accurate_latitude
  elevation: !secret accurate_elevation
  taps: 
    - name: p1
    - name: p2
```

3. **restart hass***

4. check logs

**Comment by sverleysen** [comment]
I applied the patch and changed the setup. If I increase the value of sensor.br_rain_last_hour, I so no change in the sensor.wb_irrigation_rain. Is this normal?
There are no errors in the log.

**Comment by hhaim** [comment]
The rain sensor is sampled every hour. I would add a new **variable**    and change it value to be 10 after a few hours you should be a change

**Comment by sverleysen** [comment]
Ok, will give it a try.

**Comment by hhaim** [comment]
@sverleysen another simpler idea, you could take any sensor that has a possible value (e.g. humidity/temperature) and wait a few hours.

**Comment by sverleysen** [comment]
It works! The values from sensor.wb_irrigation_rain and sensor.wb_irrigation_rain_day are updating.
I will change it back to the rain sensor and check if the values are correct. 
In the next week there will be a lot of rain, so ideal for testing :).

Thanks!

**Comment by sverleysen** [comment]
It looks like its working great now. Thanks for the help!
