### ISSUE TITLE
Rain Gauge 3D printed

### ISSUE THREAD

**Issue by iz3man** [hhaim/hass#9]
No issue, but i wanted to share my 3d printed rain gauge, which may work quite well. Atm I'm just testing it. It uses a small Zigbee Aqara Door Sensor to report open/close everytime the gauge switches.
Any idea how this can be integrated in your solution? 

![Base Gauge](https://user-images.githubusercontent.com/11553674/63179513-91f04180-c04c-11e9-9862-ba421a4904da.JPG)

![TEST](https://user-images.githubusercontent.com/11553674/63179571-b815e180-c04c-11e9-8c16-98475d54985b.JPG)

https://photos.google.com/photo/AF1QipPsEOi6qeQwNFq2c2TEBiIA5mh4LYOdDKFP-1TJ

**Comment by hhaim** [comment]
@iz3man it is simple to integrate another sensor of rain
Have a look at the other issue reported by @sverleysen
He had the same idea. (Issue #8 ) maybe he has a better sensor

**Comment by iz3man** [comment]
Why do you think my sensor is not good? This is the "standard" way mechnical sensor do the rain counting.

**Comment by hhaim** [comment]
@iz3man it is not clear to me how it works. Is there a pointer or a write up about that?
If the sensor return an incremental number of rain in mm, I can sample it (every hour) and replace the estimate value from the cloud I’m using today. You will need to add the name of the sensor.

**Comment by hhaim** [comment]
https://youtu.be/zNcW046Gmqw

**Comment by iz3man** [comment]
Exactly. This is how it works and i use a reed switch attached to it. In my case an Aqara Door switch. 
This switch goes from open to closeand vice versa by every tip.

**Comment by hhaim** [comment]
@iz3man 
the Aqara sensor (I happen to have it) is not a waterproof. Is the 3D solve it?
Do you have a sensor for accumulation of water (convert clicks to mm)?

**Comment by iz3man** [comment]
The sensor will not come in contact with water. It should be safe. 
I don't have any HA sensor for it yet. I still have to measure the amount of water it takes to make the bridge flip. Then take area of diameter of the whole can and set it into relation. But that still has to be done.

**Comment by iz3man** [comment]
It may just work with this https://www.home-assistant.io/components/counter/ and some automation. One that increments the counter with every change of sensor state and one that resets it's value at the beginning of the new hour.

**Comment by hhaim** [comment]
@iz3man I want to throw another idea. 
The Aqara Door switch was designed for door not to be a high rate counter. 
there might be an issue with what you are doing. For every rain tick there would be  ZIGBEE/MQTT/HASS. This will definitely wasn't designed  by Aqara guys and might overload the Hub/MQTT/HASS.  So first I would check if it works for a day with a simulation of rain (connect the hose to it).

**The alternative**:
I have exactly the same problem/solution with the water meter. it has a  reed sensor and can count  up to 20l/sec or 20 ticks per second. The counter in implemented inside Tasmota (ESP8266) and it reports the counters every 60/120 sec (MQTT) if the counter was changed. So MQTT factor is about 120/60*20 ~2000, 3 order of magnitude. This will filter the counters in case of a heavy rain/water . 
The Tasmota can support number of counters (water + rain) so if you have a 12 v power near the input water you could do both in the same price ..

Anyhow you should create a sensor that will report total rain mm and it should **always go up**     (not to be cleared every hour)

**Comment by iz3man** [comment]
I had the same thoughts already. The time between switches is quite long it seems. 
The Aqara switch would have the big advantage that you don't need to mess around with esp01 and deep sleep to make it run for a longer period on a single 18650 cell. 
A good idea would be to make the gauge as big as possible so you'd need quite some water to make it flip. If it flips every 30s or so the battery could last a long time i think.

**Comment by iz3man** [comment]
We had quite some rain yesterday and I was home to monitor the rain gauge. Rain was heavy (no thunderstorm or so, but a good amount of water) and the gauge was switching every 15-45s. This imho is definitely within the parameters of the Aquara switches. What do you think? I will still need to see how much water every open/close is.

**Comment by hhaim** [comment]
@iz3man 
HASS could handle event every 15sec. The question is if Aquara has an internal filter for this sensor. You will need to test it. I know that for the PIR sensors there is a filter (event every 120 sec). For the magic qube there is no filter.

**Comment by hhaim** [comment]
@iz3man I've added support for external rain sensor. have a look into #8
